@startuml Activity diagram

title: Диаграмма активности: Тарификация звонков

start

skinparam Activity {
  FontSize 13
  FontName "Arial Narrow"
}

:Запуск системы;

:Генерация звонков;

:Формирование и отправка CDR;

:Обработка CDR;

:Отправка данных в HRS;

:Получение данных в BRT;

:Занесение звонков в БД;

if (Пользователь относится к нашим абонентам?) then (да)
  :Звонок записывается в БД звонков в BRT;
else (нет)
  :Звонок не записывается в БД звонков BRT;
  stop
endif

:BRT формирует запрос в HRS;

:BRT отправляет запрос на тарификацию звонка в HRS;

:HRS получает запрос из BRT;

:HRS находит тариф по id из запроса;

if (Тариф найден?) then (да)
  :HRS считает продолжительность звонка;
  :Идёт подсчёт стоимости на основе тарифа и продолжительности звонка;
else (нет)
  :HRS отправляет ошибку: "Тариф не найден";
  stop
endif

:HRS отправляет ответ в BRT;

if (Ответ получен успешно?) then (да)
  :BRT обновляет данные в БД;
else (нет)
  :Логирование ошибки получения ответа;
endif

stop

@enduml
