@startuml

title: Просмотр подробной информации об абоненте

start
:Ввод номера абонента;
:Проверка корректности номера;

if (Номер корректен?) then (Да)
  :Поиск абонента в БД BRT;
  if (Абонент найден?) then (Да)
    :Запрос подробных данных о тарифе в БД HRS;
    if (Тариф доступен?) then (Да)
      :Отображение полной информации;
      stop
    else (Нет)
      :Ошибка: Тариф недоступен;
      end
    endif
  else (Нет)
    :Ошибка: Абонент не найден;
    end
  endif
else (Нет)
  :Ошибка: Некорректный номер;
  end
endif
@enduml
