@startuml

title: Activity Diagram: Пополнение баланса

start
:Ввод суммы пополнения;
:Проверка валидности суммы;
:Поиск абонента в БД BRT;

if (Абонент найден?) then (Да)
  :Изменение баланса;
  :Сохранение изменений в БД BRT;
  :Вывод подтверждения пополнения;
  stop
else (Нет)
  :Ошибка: Абонент не найден;
  end
endif
@enduml
