@startuml

title: Activity Diagram: Смена тарифа абонента

start
:Открытие формы смены тарифа;
:Выбор нового тарифа;
:Проверка валидности выбора;

if (Тариф доступен?) then (Да)
  :Формирование запроса на изменение тарифа;
  :Обновление тарифа абонента в BRT;
  :Обновление сущностей, параметров и их значений, приоритетов;
  :Вывод сообщения об успешной смене тарифа;
  stop
else (Нет)
  :Ошибка: Недоступный тариф;
  end
endif
@enduml
