@startuml

title: Activity Diagram: Создание нового абонента

start
:Открытие формы создания абонента;
:Ввод ФИО, номера, выбор тарифа;
:Проверка валидности данных;

if (Номер уже существует?) then (Да)
  :Ошибка: Абонент уже существует;
  end
else (Нет)
  :Проверка доступности тарифа;
  if (Тариф доступен?) then (Да)
    :Формирование запроса на регистрацию;
    :Назначение стартового баланса (100 у.е.);
    :Назначение тарифа, сущностей, приоритетов, параметоров, остатков ресурсов параметров и даты платежей;
    :Отправка данных в BRT;
    :Сохранение данных в БД;
    :Вывод сообщения об успешной регистрации;
    stop
  else (Нет)
    :Ошибка: Нет доступных тарифов;
    end
  endif
endif
@enduml